### ISSUE TITLE
Detecting other markers

### ISSUE THREAD

**Issue by ahmedsadman** [njanirudh/Aruco_Tracker#1]
Currently, the "aruco tracker.py" is detecting only the marker provided in the images. But it's not working for other markers. Can you please guide on how to detect other markers?

**Comment by njanirudh** [comment]
Can you please specify what do you mean by other types of markers?

**Comment by ahmedsadman** [comment]
It's only detecting the marker that is provided in the image folder. I am new to Aruco Marker concept, so please correct me if I am wrong

**Comment by njanirudh** [comment]
@ahmedsadman 
https://docs.opencv.org/3.3.0/d5/dae/tutorial_aruco_detection.html
Read the part about **Marker Creation**

You will have to set type of aruco dictionary

**Comment by ahmedsadman** [comment]
I want to detect the marker shown in the image. But I am failing, again and again, I tried all the dictionaries in cv2.aruco but none of them detects it.


Link to Image: http://i66.tinypic.com/1zxr5v4.jpg

Can you help me with this? I read the article you provided but that didn't help me to solve this issue

**Comment by okalachev** [comment]
@ahmedsadman , this is an incorrect marker, you probably use black background, which is overlapping with the black border.
