### ISSUE TITLE
How can I get the axis vectors?

### ISSUE THREAD

**Issue by agontarz** [njanirudh/Aruco_Tracker#10]
First of all, thank you! this works great. 

I am trying to get the x,y,z (the red ,green, and blue colored lines) as three directional vectors. Is there an easy way to do this within the aruco library?

**Comment by njanirudh** [comment]
Unfortunately I am not familiar with any other way to draw the axis pose.
I guess you will have to use the rvecs and tvecs obtained to draw it yourself.
