### ISSUE TITLE
NameError: name 'gray' is not defined

### ISSUE THREAD

**Issue by joel-sgc** [njanirudh/Aruco_Tracker#11]
When I try to run aruco_tracker.py I get

`[ WARN:0] global /io/opencv/modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video1): can't open camera by index
Traceback (most recent call last):
  File "aruco_tracker.py", line 55, in <module>
    ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)
NameError: name 'gray' is not defined`

I'm new to python and I could really use this code, can anyone help me fix this?

**Comment by aaddymehndi94** [comment]
Just change the directory 
`images = glob.glob('calib_images/checkerboard/*.jpg')`
