### ISSUE TITLE
Transformation matrix in aruco_tracker.py

### ISSUE THREAD

**Issue by pratikshaandhare** [njanirudh/Aruco_Tracker#2]
Hi,

How can I get transformation matrix (rotational matrix and translation matrix) in aruco_tracker.py. I had run the code with help of web camera it is giving me ids. Can you suggest me how can I get transformation matrix so that we will get the world co-ordinate?

Thanks in advance.

**Comment by njanirudh** [comment]
@pratikshaandhare 
Take a look at line 55 . I think thats what you want
 
#Estimate pose of each marker and return the values rvet and tvec---different from camera coefficients
rvec, tvec,_ = aruco.estimatePoseSingleMarkers(corners[0], 0.05, mtx, dist)

**Comment by pratikshaandhare** [comment]
Hi,
Thanks a lot for reply. I tried to print it. I am getting 3x1 size matrix of both rotational and translation matrix. Actually it should be of 3x3 for rotation and 3x1 for translation.
Kindly advice.

**Comment by njanirudh** [comment]
https://stackoverflow.com/questions/49219595/how-to-convert-opencv-camera-rotation-vector-to-opengl-rotation-vector

I think you have to look up how to convert rotation vector into rotation matrix

**Comment by pratikshaandhare** [comment]
Thank you. I will try this.
