### ISSUE TITLE
Aruco for mac osx

### ISSUE THREAD

**Issue by exnx** [njanirudh/Aruco_Tracker#4]
Hi, I was wondering if you had any tips on how install the Aruco library on mac osx?  It seems a bit tricky!  Thanks.

**Comment by exnx** [comment]
@njanirudh do you have any tips on this?  :/

**Comment by njanirudh** [comment]
Hew @exnx , did you install opencv?

**Comment by njanirudh** [comment]
aruco is a part of opencv library.
you can install opencv using pip

sudo apt-get install python-opencv

**Comment by exnx** [comment]
I did install opencv using pip.  Are you sure it comes with opencv already?  I am using a Mac (not Ubuntu), and I tried importing it after cv2, ie, import aruco, and no module is found.  I tried pip install aruco as well, and still can't find it.  It seems to be a c++ thing?

**Comment by exnx** [comment]
oh got it, you have to install the contrib version of opencv.

use:
pip install opencv-contrib-python

then:
from cv2 import aruco

**Comment by varagantis** [comment]
When I try to install opencv-contrib-python. a circular import error is occurring. But when I removed the contrib version, cv2 works fine. I also tried to only have contrib version and uninstalled opencv-python version and was facing "Aruco module not found" error. were you guys able to install both version at the same time?
