### ISSUE TITLE
Only single axis is displayed

### ISSUE THREAD

**Issue by natejgardner** [njanirudh/Aruco_Tracker#6]
Although squares are drawn around multiple markers, only one axis is drawn over the first marker in the list, and it often flickers between multiple markers. Ideally, axes would be displayed on all detected markers simultaneously.

**Comment by njanirudh** [comment]
Do you mean multiple markers should be detected at the same time?

**Comment by natejgardner** [comment]
Multiple markers are currently detected (i.e. boxes are drawn around them, their IDs are displayed in the list), but only one of the axes is being drawn for the pose of the first marker.

**Comment by tony950309** [comment]
in the while 1 loop, try this

    while True:
        _, frame = cap.read()
        # gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        corners, ids, _ = aruco.detectMarkers(frame, aruco_Dict, parameters=arucoParams)
        rvec, tvec, _ = aruco.estimatePoseSingleMarkers(corners, arucoMarkerEdgeLength, mtx, dist)

        frame = aruco.drawDetectedMarkers(frame, corners, ids, (0, 255, 0))  # (0,255,0)is the RGB colour of text
        if np.all(ids != None):
            for i in np.arange(ids.size):
                frame = aruco.drawAxis(frame, mtx, dist, rvec[i].reshape(1, 1, 3),
                                       tvec[i].reshape(1, 1, 3), 100)
                print('Rotation', ids.flat[i], ':')
                print(rvec[i].reshape(3))
                print('Translation', ids.flat[i], ':')
                print(tvec[i].reshape(3))

        cv2.imshow("Monitor", frame)
        if cv2.waitKey(int(1000 / fps)) & 0xFF == 27:  # if 'Esc' is pressed, quit.
            break

1. In my case, grayscale images might lead to miss-detection, so I used the RGB one.
2. _ids_, _rvec_ and _tvec_ are _np.ndarray_ type, if _m_ markers are detected, _rvec_ would have a shape of _(m,1,3)_
3. method _drawAxis_ only take _rvec_ with a shape of _(1,1,3)_, so need to reshape it ( _rvec[i]_ 's shape : _(1,3)_  )

Hope it helps

**Comment by njanirudh** [comment]
@tony950309 Thanks a lot
I will look into the changes required
