### ISSUE TITLE
calibration problem

### ISSUE THREAD

**Issue by SonOfCoding** [njanirudh/Aruco_Tracker#8]
Currently, I am using your code to get the pose of the tags. However, i am using my kinect v1 camera, do i have to calibrate my kinect v1 first in order to get correct pose?  your aruco_tracker.py read and use the Intrinsic matrix the data in test.yaml? or this line in aruco_tracker.py: ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None) calibrate my camera and get the Intrinsic matrix automatically? 

Could you please give me a help, thank you

**Comment by njanirudh** [comment]
Yes
Calibration is seperate for different cameras.
My code just shows the basic steps of calibrating a camera and using it from a yaml file.

**Comment by SonOfCoding** [comment]
i see, so your aruco_tracker.py use the yaml file's Intrinsic matrix. Which part in aruco_tracker.py should I modify in order to read my own yaml file's Intrinsic matrix? Could you please give me a hint? Thank you very much

**Comment by njanirudh** [comment]
camera_calibration.py : had the code for the camera calibration. The images are taken from the calib_images folder and the output is stored in the test.yaml inside calib_images folder.

extract_calibration.py : this file shows how to extract stored values from a file.

Replace the file path given in aruco_test.py with your calibration file path.

**Comment by SonOfCoding** [comment]
thank you very much.
