### ISSUE TITLE
Question about the accuracy of tag's pose

### ISSUE THREAD

**Issue by SonOfCoding** [njanirudh/Aruco_Tracker#9]
Hi, I am running the aruco_tracker.py. After getting my own kinect v1 's Intrinsic matrix which is 
[[1.04847513e+03 0.00000000e+00 6.66118289e+02]
 [0.00000000e+00 1.04687412e+03 5.19355741e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]

I try to get tag's pose (RT, 3*3 matrix and 3*1 matrix),  I put my camera right above the tag. I think the hight (z direction) is correct. but the x,y direction has some error, 

![Screenshot from 2019-03-09 19-40-59](https://user-images.githubusercontent.com/43914081/54071119-639f5680-42a3-11e9-909a-b74ab8635853.png)
![Screenshot from 2019-03-09 19-41-15](https://user-images.githubusercontent.com/43914081/54071120-639f5680-42a3-11e9-829b-27c1bc87c9d7.png)

I think the distance between the center of the tag and the center of my camera is nearly equal to zero. However, the result (tvec) shows -5cm and -4cm. is there a certain amount of error during detection? does the tvec need to do extra calculation?  or is there something I can change in the code to improve the accuracy? Please give me a hint, thank you

**Comment by njanirudh** [comment]
Did you calibrate for your camera?

**Comment by SonOfCoding** [comment]
yes, i did use my kinect v1 to collect chessboard photo and use your calibrate_camera.py to do the calibration. and I have changed w,h(7,6) in your code, because mine is 11,8. did I do something wrong?

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=chensy911&uid=chensy911%40live.cn&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22%E9%82%AE%E7%AE%B1chensy911%40live.cn%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
chensy911

邮箱chensy911@live.cn


签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制

On 03/10/2019 01:04, Anirudh<mailto:notifications@github.com> wrote:

Did you calibrate for your camera?

**Comment by SonOfCoding** [comment]
yes, i did use my kinect v1 to collect chessboard photo and use your calibrate_camera.py to do the calibration. and I have changed w,h(7,6) in your code, because mine is 11,8. did I do something wrong?

**Comment by matteopantano** [comment]
I am having the same issue. I did calibrate the camera but still the pose estimation is wrong

**Comment by njanirudh** [comment]
@matteopantano @SonOfCoding  unfortunately i dont have much time to debug and research about that now..please if you find the result submit a pull request

**Comment by matteopantano** [comment]
Issue found, the problem was on the camera resolution. OpenCV by default opens 4:3. However, calibration was done on 16:9. Calibration resolution and opencv resolution must match.
